### ISSUE TITLE
ValueError: Not able to find the options for equities

### ISSUE THREAD

**Issue by ALee008** [JerBouma/FinanceDatabase#1]
**Describe the bug**
Was trying to view all available equities, but I am getting a ValueError which follows a JSONDecodeError (see screenshot). 

**To Reproduce**
`
import FinanceDatabase as fd

equities = fd.show_options('equities')
print(equities)
`

**Expected behavior**
show all available equities

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39236016/106965784-713a1100-6744-11eb-8cfa-89c1ece917b8.png)

**Desktop (please complete the following information):**
 - OS: OSX El Capitan

**Comment by JerBouma** [comment]
The point of show options is to give you information on things like countries, sectors, industries, categories and such.

In this case you need to include either 'countries', 'sectors' or 'industry' as second variable to the function. The fact it doesn't work with just equities is a bug I will fix later.

If you want all equities symbols you should use the function _fd.select_equities()_ without any input.

**Comment by ALee008** [comment]
Thank you for the quick response. I tried etfs, which worked. I tested show 'something' because I was curious about the message if an option was not available. It returned a ValueError and printing all available options, equity was one of them. That's why I tried this option.

**Comment by JerBouma** [comment]
Fixed this issue, if you now enter 'equities' you get countries, sectors and industries, see image below. Please update to version 0.1.6 by doing the following:
`pip install FinanceDatabase --upgrade`

![image](https://user-images.githubusercontent.com/46355364/107013130-3ebb0300-679a-11eb-8604-d116b405ca64.png)
