### ISSUE TITLE
AttributeError is raised when calling select_etfs() with no parameter given

### ISSUE THREAD

**Issue by jstesta** [JerBouma/FinanceDatabase#10]
**Describe the bug**
AttributeError is raised when calling select_etfs() with no parameter given.

**Expected behavior**
Method returns all ETFs.

**Actual behavior**
The following error is raised:
> Traceback (most recent call last):
>   File "..snip..\lib\site-packages\FinanceDatabase\json_picker.py", line 113, in select_etfs
>     json_data = json.loads(request.text).decode("UTF-8")
> AttributeError: 'dict' object has no attribute 'decode'

**Additional context**
Version 0.1.9

**Comment by JerBouma** [comment]
Will look into this later this week. Seems it doesn't select the right JSON file.

**Comment by JerBouma** [comment]
Fixed this issue in version 0.1.10, please upgrade.
