### ISSUE TITLE
Display Industry set

### ISSUE THREAD

**Issue by AntoineFinance** [JerBouma/FinanceDatabase#12]
Hi, 

Thank you very much for this great module,  I had been trying to do something similar for some time.

I have been trying to query your database for the equity data for a specific industry and I have found out that it can be difficult to know which industries are available without looking into the json files at FinanceDatabase/Database/Categories/.

Have I missed something here and there is already a function to display the industries ?

If not, do you think that it would be a good idea to add a feature that would list the available industries or other sets of values that are available for the different arguments? 

As a solution, I would consider something that would just read the existing json files and display their contents as set objects.

Maybe just a summary of the database structure would be ideal as it would encompass everything and seems like the most helpful feature overall.

Thank you.

PS: I'm keen to help with the implementation if it helps.

**Comment by JerBouma** [comment]
I believe this is what you are looking for:

**show_options(product, equities_selection=None)**

Gives all available options from the functions below per product (i.e. Equities, Funds) which then can be used to collect data. You can select a sub selection of equities by entering 'countries', 'sectors' or 'industries' for equities_selection.

This is from the README. Let me know if this is not enough!

**Comment by AntoineFinance** [comment]
Thank you very much @JerBouma, your advice works well and was exactly what I was looking for.
I think that adding it as an example in the README could help a bit but you're right, it's already explained there.

**Comment by JerBouma** [comment]
No problem! Will add this into the Examples section just so others won't miss it.

**Comment by AntoineFinance** [comment]
Thank you very much @JerBouma
