### ISSUE TITLE
Download ETF data by countries

### ISSUE THREAD

**Issue by Soga-no-Tojiko** [JerBouma/FinanceDatabase#19]
Just an expectation for enhancement. I am currently working on analyzing ETFs issued in North America region (roughly America). While it is possible to download these data via selenium, I wish you could add another country option in the function "select_etfs" as well as the function "select_equities". I would appreciate it if you could consider this.

**Comment by JerBouma** [comment]
I know this is a bit late but this is actually a possibility by using the `country` argument for equities and by searching for keywords for ETFs. See below:

```python
import financedatabase as fd

# Obtain United States Equities
united_states_equities = fd.select_equities(country="United States")

# Obtain all ETFs.
etfs = fd.select_etfs()

# Search ETFs
united_states_etfs = fd.search_products(etfs, query='United States')
```

Which returns:

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/46355364/213470082-6caf518d-f552-4ad9-8e9b-6065daa1812d.png">
