### ISSUE TITLE
some ETF symbols have non-alphabetic characters

### ISSUE THREAD

**Issue by HamidM6** [JerBouma/FinanceDatabase#25]
**Describe the bug**
some ETF symbols have non alphabetic characters

**To Reproduce**
`
import financedatabase as fd

res = fd.select_etfs()

for k,v in res.items():
    if k.isalpha() is False:
        print(k)
`

**Screenshots**

![image](https://user-images.githubusercontent.com/33704063/196719026-7d8849a5-5c86-4fea-b4fa-2356933598d6.png)

**Comment by JerBouma** [comment]
Why is this an issue? There is little information about these tickers but they do exist.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/46355364/196731279-da85a640-fe01-494c-9852-09ba38971637.png">

**Comment by HamidM6** [comment]
You are right. This is an awesome tool. thank you for all the work.
