### ISSUE TITLE
[BUG] No required/depends clauses in setup.py/pyproject.toml

### ISSUE THREAD

**Issue by yurivict** [JerBouma/FinanceDatabase#32]
At least pandas should be in the dependency list.

**Comment by JerBouma** [comment]
Good catch, any other suggestions other than pandas?

**Comment by yurivict** [comment]
You can 'grep import *' and see what other dependencies does it install.

**Comment by JerBouma** [comment]
Conclusion is it's just `pandas`. I've added in the line within `setup.py` so this should now be clear.
 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/46355364/221532138-a65f7e30-e375-4352-9c8a-3af664cc72c4.png">
