### ISSUE TITLE
[DATA] - Added Kenya Agriculturals

### ISSUE THREAD

**Issue by nindogo** [JerBouma/FinanceDatabase#35]
**What did you improve in the Database?**
Added new data from Kenya - Agriculturals as shown [here](https://www.nse.co.ke/listed-companies/)
A description of what's data you improved, deleted or added, and a bit of context (why is that).
I did this because Kenya is not on the list. I do not know how to do it well so this is a trial.
There is a local symbol (should I add a prefix?) and the ISIN code - I added 2 rows for every record.

I will work on the rest if this is ok.

**Drop the files you have updated below**
Did a ZIP (no passwords) because the file is more than 25Mb raw
[equities.zip](https://github.com/JerBouma/FinanceDatabase/files/10931958/equities.zip)

**Comment by JerBouma** [comment]
Thank you, keep it coming!
