### ISSUE TITLE
Failed downloads

### ISSUE THREAD

**Issue by Japemen** [JerBouma/FinanceDatabase#41]
Ik kan niets downloaden dus ik denk dat Yahoo weer iets aangepast heeft..... Kan/ga je dit aanpassen?

**Comment by JerBouma** [comment]
Er zit geen enkele koppeling tussen Yahoo Finance en deze database dus dat ligt hierbuiten.

Welke error krijg je?

**Comment by Japemen** [comment]
Goedemorgen Jeroen,

Ik krijg de error : 315 Failed downloads.
Achter elke ticker staat dan “No data found for this range, symbol may be delisted”. Terwijl ik de ticket via financedatabase ophaal, dit doe ik via etfs.search().
Elke voorbeelden van tickers die ik gebruik zijn:
TGET.AS
IWDE.AS
V40A.AS
WPAD.AS
Dus hij kan de historische data niet meer ophalen. Als je het fijn vindt kan je wel mijn code toesturen.

P.S. Ik zag dat je bij ASR werkte. Heb ik ook jaren gewerkt bij Inkomen als relatiebeheerder. Mooi bedrijf met een goede cultuur.

Met vriendelijke groeten,


Jaap Hoeve

Tel.: +31614206642
LinkedIn: www.linkedin.com/in/jaaphoeve<http://www.linkedin.com/in/jaaphoeve>

From: Jeroen Bouma ***@***.***>
Date: Friday, 9 June 2023 at 09:19
To: JerBouma/FinanceDatabase ***@***.***>
Cc: Japemen ***@***.***>, Author ***@***.***>
Subject: Re: [JerBouma/FinanceDatabase] Failed downloads (Issue #41)

Er zit geen enkele koppeling tussen Yahoo Finance en deze database dus dat ligt hierbuiten.

Welke error krijg je?

**Comment by Japemen** [comment]
Hoi Jeroen,

Dat klopt! Bedankt voor de oplossing. Ik gebruikte de oude yfinance.

Met vriendelijke groeten,


Jaap Hoeve

Tel.: +31614206642
LinkedIn: www.linkedin.com/in/jaaphoeve<http://www.linkedin.com/in/jaaphoeve>

From: Jeroen Bouma ***@***.***>
Date: Friday, 9 June 2023 at 10:35
To: JerBouma/FinanceDatabase ***@***.***>
Cc: Japemen ***@***.***>, Author ***@***.***>
Subject: Re: [JerBouma/FinanceDatabase] Failed downloads (Issue #41)

Check even of je wel op de juiste versie zit als je yfinance gebruikt. In principe moet alles namelijk gewoon werken. Zie onderstaand.
[image]<https://user-images.githubusercontent.com/46355364/244639017-9f5fef5f-3b84-46ce-ae30-976f4cc7a799.png>

Kan zijn dat een aantal tickers niet meer in de dataset zitten van Yahoo Finance, dat is puur omdat de FinanceDatabase rekening houdt met survivorship bias, ik haal dus niet tickers weg puur omdat het product niet meer bestaat.
