### ISSUE TITLE
[IMPROVE]  remove accented characters from name column

### ISSUE THREAD

**Issue by maread99** [JerBouma/FinanceDatabase#42]
Hi, what an awesome resource you've put together here! Thank you.

I've noticed that some of the entries have accented characters in the name column which don't appear to decode correctly (at least for me), for example:
```python
equities.search(name="telef", exchange="MCE")
```
![image](https://github.com/JerBouma/FinanceDatabase/assets/56914820/28a4880e-73ed-486c-b3df-cf150c3f6b93)
So neither of the following return anything:
```python
>>> df = equities.search(name="telefonica", exchange="MCE")
>>> df.empty
True
>>> equities.search(name="telefónica", exchange="MCE")
>>> df.empty
True
```
The following returns a load of instruments because many entries for Telefonica do not included the accented 'o':
```python
>>> df = equities.search(name="telefonica")
>>> len(df)
20
```
...although it won't include the Madrid listing (and other entries that have the accented o in the name).

**To ensure consistent querying I'd suggest replacing all accented characters in the name column with their unaccented equivalents.**

If I get a moment (unlikely tbh) I'll contribute the change. Thought I'd raise the issue in the meantime in case anyone else runs into this and has the opportunity to make the changes.

Thanks again for the library!
Marcus

**Comment by JerBouma** [comment]
Good call! Should also include a Boolean ("accent_sensitive") parameter in case you do want to search specifically for "telephóne" instead of "telephone".
