### ISSUE TITLE
[FR] Multiple criteria while searching

### ISSUE THREAD

**Issue by ucabqll** [JerBouma/FinanceDatabase#45]
Hi,

Thanks for the project! I was wondering whether or not it would be a good idea to add support for multiple parameters when performing a search function. Currently, this could certainly be performed by joining multiple data frames that are returned via the search function or just by querying the entire dump at once and filter it by ourselves. But I think it would be more convenient if this feature is built in to the function? 

For example, to filter for both Large Cap & Mid Cap tech listed in NASDAQ it could be something like: 

`equities.search(country='United States', sector='Tech', market='NASDAQ', market_cap=['Large Cap', 'Mid Cap'])`

Or perhaps there is already something available, if so I apologise.

**Comment by JerBouma** [comment]
This is definitely a good suggestion. I'll put some attention into this and #42 soon!

**Comment by JerBouma** [comment]
This issue has been fixed, please update to v2.1.1.

<img width="1121" alt="image" src="https://github.com/JerBouma/FinanceDatabase/assets/46355364/2f3a8358-498d-4218-b466-9b39003d9c6c">
