### ISSUE TITLE
[IMPROVE] The 'pathlib' module is used but it doesn't appear in the dependencies section in pyproject.toml

### ISSUE THREAD

**Issue by yurivict** [JerBouma/FinanceDatabase#46]
Version: 2.1.1

**Comment by JerBouma** [comment]
Hi! This shouldn't be an issue given that pathlib is an internal module. As an example I created a new environment (with Python 3.8) and installed the FinanceDatabase and it worked fine. Could you elaborate why this is an issue?

![image](https://github.com/JerBouma/FinanceDatabase/assets/46355364/837d6aaa-322d-42e0-ba34-ba37750d5a75)

**Comment by yurivict** [comment]
You are right.
Thank you.
