### ISSUE TITLE
[DATA] Added MBG.DE and DTG.DE

### ISSUE THREAD

**Issue by desaijimmy** [JerBouma/FinanceDatabase#70]
**What did you improve in the Database?**
Daimler company split in two operating and listed companies: Mercedes-Benz (for cars) and Daimler Trucks. DAI.DE no longer trades and the two new listed stocks are MBG.DE and DTG.DE. I added the two entries at the end of the current file. 

**Drop the files you have updated below (compress to zip if file size too large)**
[equities.zip](https://github.com/JerBouma/FinanceDatabase/files/13763066/equities.zip)

**Comment by JerBouma** [comment]
Updated the database with these additions, thank you!
