### ISSUE TITLE
[DATA] Fixed data for FFH.TO

### ISSUE THREAD

**Issue by desaijimmy** [JerBouma/FinanceDatabase#71]
**What did you improve in the Database?**
Data for the symbol FFH.TO was incorrect. Correct company is Fairfax Financial from Canada, not X Financial from China. 

Just wondering: Is there a proper method to validate new changes submitted by users? Otherwise propensity for human induced errors would be quite high. 

**Drop the files you have updated below (compress to zip if file size too large)**
[equities.zip](https://github.com/JerBouma/FinanceDatabase/files/13767127/equities.zip)

**Comment by JerBouma** [comment]
Thanks for the PRs, will have a look soon. To answer your question, not really other than manual Google searches!

**Comment by desaijimmy** [comment]
Thanks Jeroen!

I found a number of other issues (e.g. symbols CAF, EDD, IIF, MS, MSD, etc. all have the name "Morgan Stanley"). Can we connect directly (email) to discuss further? Thanks.

**Comment by JerBouma** [comment]
> Thanks Jeroen!
> 
> I found a number of other issues (e.g. symbols CAF, EDD, IIF, MS, MSD, etc. all have the name "Morgan Stanley"). Can we connect directly (email) to discuss further? Thanks. 

Hi! Interesting, that doesn't seem right. We can chat via LinkedIn (https://www.linkedin.com/in/boumajeroen) or otherwise jer.bouma@gmail.com

**Comment by JerBouma** [comment]
Updated the database with these additions, thank you!
