### ISSUE TITLE
Missing US symbols

### ISSUE THREAD

**Issue by mrx23dot** [JerBouma/FinanceDatabase#8]
Hello,
I found these US stocks missing from "united_states.json"
[diff.txt](https://github.com/JerBouma/FinanceDatabase/files/6267478/diff.txt)

They seems active based on my broker.

Cheers

**Comment by JerBouma** [comment]
Kind of need to re-run the whole database and remove some restrictions I placed. It is difficult to capture truly _all_ available symbols and companies. I need to think about using functionality like Threading or Multi Core processing to speed up the process.

For now I am closing this issue and will include these tickers in a future version.

**Comment by JerBouma** [comment]
I am re-running the database right now. This wil take a couple of weeks but I will add these tickers to the total if they are not yet included.

**Comment by JerBouma** [comment]
Database updated! All your symbols are included. Please update to FinanceDatabase >= 0.1.9 to use the new database.
