### ISSUE TITLE
Error by:  core_selection = fd.select_etfs("core_selection_degiro_filtered") 

### ISSUE THREAD

**Issue by thomas2004ch** [JerBouma/FinanceDatabase#9]
Hi,

As I run the code:
...
core_selection = fd.select_etfs("core_selection_degiro_filtered")
...
I got error as follow:
`JSONDecodeError                           Traceback (most recent call last)
~\anaconda3\lib\site-packages\FinanceDatabase\json_picker.py in select_etfs(category)
    105             request = requests.get(json_file)
--> 106             json_data = json.loads(request.text)
    107         except json.decoder.JSONDecodeError:

~\anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:

~\anaconda3\lib\json\decoder.py in decode(self, s, _w)
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj

JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-17-bb6bc10717f4> in <module>
----> 1 core_selection = fd.select_etfs("core_selection_degiro_filtered")
      2 # core_selection = fd.select_etfs("")
      3 # core_selection

~\anaconda3\lib\site-packages\FinanceDatabase\json_picker.py in select_etfs(category)
    106             json_data = json.loads(request.text)
    107         except json.decoder.JSONDecodeError:
--> 108             raise ValueError(f"Not able to find any data for {category}.")
    109     else:
    110         try:

ValueError: Not able to find any data for core_selection_degiro_filtered.`

**Comment by JerBouma** [comment]
Hi Thomas,

Great catch. This doesn't match anymore with the naming in the Database. See [here](https://github.com/JerBouma/FinanceDatabase/tree/master/Database/ETFs). Thus it should be: `core_selection = fd.select_etfs("core_selection_filtered")`

Will adjust in README.md now.

**Comment by thomas2004ch** [comment]
great, thanks!
     Am Freitag, 11. Juni 2021, 15:04:30 MESZ hat Jeroen Bouma ***@***.***> Folgendes geschrieben:  
 
 


Hi Thomas,

Great catch. This doesn't match anymore with the naming in the Database. See here. Thus it should be: core_selection = fd.select_etfs("core_selection_filtered")

Will adjust in README.md now.

**Comment by thomas2004ch** [comment]
[Finance Database.txt](https://github.com/JerBouma/FinanceDatabase/files/6649271/Finance.Database.txt)

Since here doesn't support upload notebook file. I change the supress to .txt. Please download it and change it to .ipynb

**Comment by thomas2004ch** [comment]
sorry, change the file type back to .ipynb.

**Comment by JerBouma** [comment]
![image](https://user-images.githubusercontent.com/46355364/121914362-7af70500-cd32-11eb-8426-07ee5c0c905b.png)

Exactly same result. Sorry man, it really is on your side. I can't do much more troubleshooting than this.

**Comment by thomas2004ch** [comment]
I use Python 3.7. It this OK?

     Am Montag, 14. Juni 2021, 17:04:48 MESZ hat Jeroen Bouma ***@***.***> Folgendes geschrieben:  
 
 




Exactly same result. Sorry man, it really is on your side. I can't do much more troubleshooting than this.
